### ISSUE TITLE
Streamer is always generated with a TCDM data width of 64

### ISSUE THREAD

**Issue by RickLuiken** [KULeuven-MICAS/snax_cluster#189]
Setting the data_width in the cluster configuration does not change the TCDM data width parameter in the generated streamer files.

Seems like it is not set in hw/templates/stream_param_gen.scala.tpl

**Comment by rgantonio** [comment]
Hi @RickLuiken! Thanks for this, I will ask @xiaoling-yi about this part since she made the streamer.

Please note that some of us are on vacation so expect very late replies. But we will address these concerns 😄

**Comment by RickLuiken** [comment]
Hi @rgantonio !

Thanks for the reply. I can work around this for now. Enjoy your holidays!

**Comment by xiaoling-yi** [comment]
Hi @RickLuiken thanks for pointing this out! I will fix it later!

**Comment by xiaoling-yi** [comment]
Close as finished.
