### ISSUE TITLE
Make a header file generator streamers

### ISSUE THREAD

**Issue by rgantonio** [KULeuven-MICAS/snax_cluster#246]
We're missing a support function to generate the headerfiles just like how @IveanEx does for the xDMA.

We need to make one for the streamers too. How do we approach this?

Options:
- Use template generation again?
- Use the Chisel method of @IveanEx?

@IveanEx and @xiaoling-yi what do you guys think? I think it is a MUST HAVE at the moment so that other users won't find it confusing to see what CSR registers are available for the streamers.

**Comment by IveanEx** [comment]
I and @xiaoling-yi are working on a new global streamer with xdma streamer infrastructure, which involves a new StreamerTop. I think this can be added, and the way of passing arguments can also be improved. 😳😳

**Comment by rgantonio** [comment]
Bump @xiaoling-yi and @IveanEx can this be a priority? :)

So we can help Mace and Jun's integration as well. I mean if it's alright? hehe

**Comment by xiaoling-yi** [comment]
I will find some time to do this! @rgantonio

**Comment by xiaoling-yi** [comment]
Close as finished
