### ISSUE TITLE
Change CSR writes and reads with the built-in `csrw_ss` and `csrr_ss` functions

### ISSUE THREAD

**Issue by rgantonio** [KULeuven-MICAS/snax_cluster#247]
Looking at PR #194 we need to change several lines. I suggest we start to modify the register functions with @IveanEx's fix. This avoids changing too many lines, but it would be better just to change the header file of the added registers. It should be a cleaner and more elegant way of doing things.

**Comment by xiaoling-yi** [comment]
Close as finished.
