### ISSUE TITLE
Improving the generation of Bender targets

### ISSUE THREAD

**Issue by IveanEx** [KULeuven-MICAS/snax_cluster#294]
From our experience in development, the inconsistency between enabled bender targets and selected snax cfg is one of the common errors. HeMAiA [PR #25](https://github.com/KULeuven-MICAS/HeMAiA/pull/25) provides a new way to manage these bender targets by coupling targets and snax cfg to avoid the error. This idea can also be integrated into snax.

**Comment by rgantonio** [comment]
@IveanEx PR #304 solves this!
