### ISSUE TITLE
Update snax-gemm-engine test to use block GEMM

### ISSUE THREAD

**Issue by rgantonio** [KULeuven-MICAS/snax_cluster#44]
Please refer to PR #42 for more details! Basically same test but use block GEMM.

**Comment by xiaoling-yi** [comment]
Not yet. This snax-gemm-engine is just a subset of snax-block-gemm with `M = K = N =1`. Maybe we can just remove this test?

**Comment by rgantonio** [comment]
This is old and was resolved with new implementations.
