### ISSUE TITLE
Address failing tests in CI

### ISSUE THREAD

**Issue by JosseVanDelm** [KULeuven-MICAS/snax_cluster#45]
Apparently sometimes the run tests step of CI fails tests, but does not report so?

**Comment by rgantonio** [comment]
Is this fixed already?

@xiaoling-yi ?

**Comment by xiaoling-yi** [comment]
Hi, the ci fails test is solved but the ci test fail doesn't report hasn't been solved. I should figure out how the error code propagates in ci and then fix it. Currently, I have no idea about it.

**Comment by JosseVanDelm** [comment]
@xiaoling-yi did we check last time whether the error appeared on `core_id == 0` ?
I vaguely remember that this is something that the simulator does, but I thought we checked this last time and that that was not the issue here, right?

**Comment by rgantonio** [comment]
This is cleaned in the latest one.
