### ISSUE TITLE
Wrong docker container image in tutorial

### ISSUE THREAD

**Issue by mace1997** [KULeuven-MICAS/snax_cluster#50]
Hi @rgantonio,

It seems the documentation is referring to using `ghcr.io/pulp-platform/snitch_cluster:latest` but you actually need `docker.io/rgantonio/snax-chisel-test`.

Thanks!

Bye

**Comment by rgantonio** [comment]
Hi @mace6868!

Good point, it was an added adjustment just last week 😄 
I will make a PR to update it. Thanks!

**Comment by JosseVanDelm** [comment]
@rgantonio
We noticed that the `make traces` is also not working.
The installation of `spike-dasm` is not mentioned in the tutorial, maybe you can also address that in the same PR?

**Comment by rgantonio** [comment]
Yup! But I plan to make a separate "SW PR" though. I'll make 2 separate ones:

(1) For fixing loose ends PR
(2) For the SW PR tutorial

**Comment by JosseVanDelm** [comment]
@rgantonio I see, but it's not referenced in your quickstart, so people will not see it?

**Comment by rgantonio** [comment]
Oh good lord that's weird haha XD

**Comment by rgantonio** [comment]
This was fixed with PR #132
