### ISSUE TITLE
Reuse hardware build for multiple software tests?

### ISSUE THREAD

**Issue by JosseVanDelm** [KULeuven-MICAS/snax_cluster#67]
It dawned on me but I wonder if we can re-use the same `sw-snax-mac-cluster-vlt` and just build a new SW so we don't need to do multiple HW builds?

So the idea is, build SW for the original one then build for the generic one. Test them differently since we already have the yamls separated? :)

_Originally posted by @rgantonio in https://github.com/KULeuven-MICAS/snitch_cluster/pull/57#discussion_r1432444324_

**Comment by rgantonio** [comment]
This is being implemented already!
