### ISSUE TITLE
Add generic runtime documentation

### ISSUE THREAD

**Issue by JosseVanDelm** [KULeuven-MICAS/snax_cluster#69]
🤯 This is super nice!

I can't notice anything wrong, but I'm not super familiar with the codebase.

It might be useful to include the PR documentation and support matrix to the documentation for future reference. If we add custom support for something in a specific combination of toolchain-runtime, we can keep track of this nicely.

Also the support matrix in a following format looks more clear to me:

<table>
  <tr>
    <th>Runtime</th>
    <th>rtl</th>
    <th colspan="2">rtl-generic</th>
  </tr>
  <tr>
    <th> Toolchain </th>
    <th colspan="2">llvm-snitch</th>
     <th>llvm-generic</th>
  </tr>
<tr>
    <td class="tg-0pky">LLVM Version</td>
    <td class="tg-0pky">12 :x:</td>
    <td class="tg-0pky">12 :x:</td>
    <td class="tg-0pky">17 :heavy_check_mark:</td>
  </tr>
  <tr>
    <td class="tg-0pky">Custom Instructions</td>
    <td class="tg-0pky">:heavy_check_mark:</td>
    <td class="tg-0pky">:heavy_check_mark:</td>
    <td class="tg-0pky">:x:</td>
  </tr>
  <tr>
    <td class="tg-0pky">OpenMP Support</td>
    <td class="tg-0pky">:heavy_check_mark:</td>
    <td class="tg-0pky">:x:</td>
    <td class="tg-0pky">:x:</td>
  </tr>
  <tr>
    <td class="tg-0pky">SSR Support</td>
    <td class="tg-0pky">:heavy_check_mark:</td>
    <td class="tg-0pky">:x:</td>
    <td class="tg-0pky">:x:</td>
  </tr>
  <tr>
    <td class="tg-0pky">Data Mover Support</td>
    <td class="tg-0pky">:heavy_check_mark:</td>
    <td class="tg-0pky">:x:</td>
    <td class="tg-0pky">:x:</td>
  </tr>
</table>

_Originally posted by @jorendumoulin in https://github.com/KULeuven-MICAS/snitch_cluster/pull/57#pullrequestreview-1790355842_

**Comment by rgantonio** [comment]
Our current CI implements this too!
